# Generated by Django 2.0.1 on 2018-07-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180602_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('reemail', '修改邮箱')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
